# Generated by Django 4.1.2 on 2024-07-05 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_carrito_carritoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='categoria',
            field=models.CharField(choices=[('Procesadores', 'Procesadores'), ('Placa Madre', 'Placa Madre'), ('Tarjetas de Video', 'Tarjetas de Video'), ('RAM', 'RAM'), ('Fuentes de Poder', 'Fuentes de Poder'), ('Almacenamiento', 'Almacenamiento'), ('Gabinetes', 'Gabinetes'), ('Refrigeración', 'Refrigeración'), ('Notebooks', 'Notebooks'), ('PC', 'PC')], max_length=20),
        ),
    ]
